insert into documenttype (name, extension, mimetype) values('Portable Document Format', 'pdf', 'application/pdf');
insert into documenttype (name, extension, mimetype) values('Text', 'txt', 'text/plain');
insert into documenttype (name, extension, mimetype) values('Microsoft Word', 'doc', 'application/msword');
insert into documenttype (name, extension, mimetype) values('Microsoft Word', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
insert into documenttype (name, extension, mimetype) values('Microsoft Excel', 'xls', 'application/msexcel');
insert into documenttype (name, extension, mimetype) values('Microsoft Excel', 'xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
insert into documenttype (name, extension, mimetype) values('Microsoft Powerpoint', 'ppt', 'application/msexcel');
insert into documenttype (name, extension, mimetype) values('Microsoft Powerpoint', 'pptx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
insert into documenttype (name, extension, mimetype) values('Graphics Interchange Format', 'gif', 'image/gif');
insert into documenttype (name, extension, mimetype) values('Portable Network Graphics', 'png', 'image/png');
insert into documenttype (name, extension, mimetype) values('JPEG', 'jpg', 'image/jpeg');
insert into documenttype (name, extension, mimetype) values('JPEG', 'jpeg', 'image/jpeg');
insert into documenttype (name, extension, mimetype) values('TIFF', 'tif', 'image/tiff');
