CREATE USER 'hellodoc'@'localhost' IDENTIFIED BY 'hellodoc';
CREATE DATABASE hellodoc CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE hellodoc_dev CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON hellodoc.* TO 'hellodoc'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON hellodoc_dev.* TO 'hellodoc'@'localhost';
